apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: ain3003projectregistryf
        image: ain3003projectregistryf.azurecr.io/ain3003-project:latest
        ports:
        - containerPort: 50505
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
 
